### ISSUE TITLE
Allow splitTender for partial captured funds

### ISSUE THREAD

**Issue by nneuberger1** [square/reader-sdk-flutter-plugin#104]
Does the `allowSplitTender` setting detect a card transaction when the charge placed is say $5.00 and the transaction returns it was approved for $4.00 and thus we need to get another transaction for $1.00 ?

I wasn't sure if Square has that capability to charge a card only part of the requested payment amount.

Or is this `allowSplitTender` field only used for like splitting the payment in a scenario at a restaurant like 'split the check'?

`builder.amountMoney = MoneyBuilder()`
`builder.allowSplitTender = true;`

I did noticed if I set it to true, it does display the 'Split Tender' button at the top. I'm just wondering if there is a capability like the above.

**Comment by saragemmell** [comment]
If you have the ability to split tender than you can use allowPartialAuthorization to get that behavior. Note that if allowPartialAuthorization is true and payment source is any of cash/other/balance/bankAccount then we will pass false in even if the developer passes it as true because partialAuthorization is only allowed for card payments.

**Comment by saragemmell** [comment]
allowSplitTender can only be used for a scenario like “split the check” and we don’t support partial authorization.
